name: tracking
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  camera: ^0.10.5+9
  chewie: ^1.11.3
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  image: ^4.1.7
  image_picker: ^1.1.2
  lottie: ^3.0.0
  modal_progress_hud_nsn: ^0.5.0
  onnxruntime: ^1.4.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.3.4
  tflite_flutter: ^0.11.0
  video_player: ^2.9.5
  http: ^1.1.0
  path: ^1.8.3
  web_socket_channel: ^3.0.3
  flutter_image_compress: ^2.4.0
  http_parser: ^4.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lottie.json
    - assets/Screenshot_2025-04-06_140942-removebg-preview.png
    - assets/detection-removebg-preview.png
    - assets/download.png
    - assets/download__2_-removebg-preview.png
    - assets/Animation - 1745343702961.json

  # fonts:
  #   - family: Schyler
  #     fonts:
        # - asset: fonts/IndieFlower-Regular.ttf
